# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyDataLogger01GUI.ui'
#
# Created: Thu May 07 12:03:09 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1038, 680)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(1004, 367))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.textEditTerminal = QtGui.QTextEdit(self.layoutWidget)
        self.textEditTerminal.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEditTerminal.sizePolicy().hasHeightForWidth())
        self.textEditTerminal.setSizePolicy(sizePolicy)
        self.textEditTerminal.setMinimumSize(QtCore.QSize(256, 315))
        self.textEditTerminal.setObjectName(_fromUtf8("textEditTerminal"))
        self.verticalLayout.addWidget(self.textEditTerminal)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnClear = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClear.sizePolicy().hasHeightForWidth())
        self.btnClear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.horizontalLayout_2.addWidget(self.btnClear)
        self.btnPlot = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.btnPlot.setFont(font)
        self.btnPlot.setObjectName(_fromUtf8("btnPlot"))
        self.horizontalLayout_2.addWidget(self.btnPlot)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.dataView = PlotWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.dataView.sizePolicy().hasHeightForWidth())
        self.dataView.setSizePolicy(sizePolicy)
        self.dataView.setMinimumSize(QtCore.QSize(741, 371))
        self.dataView.setResizeAnchor(QtGui.QGraphicsView.NoAnchor)
        self.dataView.setObjectName(_fromUtf8("dataView"))
        self.verticalLayout_2.addWidget(self.splitter)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.tabControl = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabControl.sizePolicy().hasHeightForWidth())
        self.tabControl.setSizePolicy(sizePolicy)
        self.tabControl.setMinimumSize(QtCore.QSize(1000, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.tabControl.setFont(font)
        self.tabControl.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabControl.setObjectName(_fromUtf8("tabControl"))
        self.tabCmd = QtGui.QWidget()
        self.tabCmd.setObjectName(_fromUtf8("tabCmd"))
        self.texCMDtBrowser = QtGui.QTextBrowser(self.tabCmd)
        self.texCMDtBrowser.setGeometry(QtCore.QRect(425, 9, 564, 163))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.texCMDtBrowser.sizePolicy().hasHeightForWidth())
        self.texCMDtBrowser.setSizePolicy(sizePolicy)
        self.texCMDtBrowser.setObjectName(_fromUtf8("texCMDtBrowser"))
        self.label_2 = QtGui.QLabel(self.tabCmd)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 63, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEditCMD = QtGui.QLineEdit(self.tabCmd)
        self.lineEditCMD.setGeometry(QtCore.QRect(79, 10, 281, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCMD.sizePolicy().hasHeightForWidth())
        self.lineEditCMD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.lineEditCMD.setFont(font)
        self.lineEditCMD.setObjectName(_fromUtf8("lineEditCMD"))
        self.tabControl.addTab(self.tabCmd, _fromUtf8(""))
        self.tabSerial = QtGui.QWidget()
        self.tabSerial.setObjectName(_fromUtf8("tabSerial"))
        self.label_6 = QtGui.QLabel(self.tabSerial)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 511, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tabSerial)
        self.label_7.setGeometry(QtCore.QRect(420, 20, 561, 71))
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.layoutWidget1 = QtGui.QWidget(self.tabSerial)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 211, 76))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.cbPorts = QtGui.QComboBox(self.layoutWidget1)
        self.cbPorts.setMaxVisibleItems(10)
        self.cbPorts.setObjectName(_fromUtf8("cbPorts"))
        #self.cbPorts.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.cbPorts)
        self.btnRescan = QtGui.QPushButton(self.layoutWidget1)
        self.btnRescan.setObjectName(_fromUtf8("btnRescan"))
        self.verticalLayout_3.addWidget(self.btnRescan)
        self.layoutWidget2 = QtGui.QWidget(self.tabSerial)
        self.layoutWidget2.setGeometry(QtCore.QRect(230, 20, 161, 46))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.cbBaudrate = QtGui.QComboBox(self.layoutWidget2)
        self.cbBaudrate.setObjectName(_fromUtf8("cbBaudrate"))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.cbBaudrate)
        self.layoutWidget3 = QtGui.QWidget(self.tabSerial)
        self.layoutWidget3.setGeometry(QtCore.QRect(820, 140, 166, 26))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.btnSerialStart = QtGui.QPushButton(self.layoutWidget3)
        self.btnSerialStart.setEnabled(False)
        self.btnSerialStart.setObjectName(_fromUtf8("btnSerialStart"))
        self.horizontalLayout_3.addWidget(self.btnSerialStart)
        self.tabControl.addTab(self.tabSerial, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabControl)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        self.statusbar.setFont(font)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionClear = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/edit-clear-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/document-save-5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionPortsetting = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/system-run-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPortsetting.setIcon(icon2)
        self.actionPortsetting.setObjectName(_fromUtf8("actionPortsetting"))
        self.actionTerminalsetting = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/preferences-system-session-manager.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTerminalsetting.setIcon(icon3)
        self.actionTerminalsetting.setObjectName(_fromUtf8("actionTerminalsetting"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/application-exit-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/help-about-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSetting.addAction(self.actionPortsetting)
        self.menuSetting.addAction(self.actionTerminalsetting)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPortsetting)
        self.toolBar.addAction(self.actionTerminalsetting)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)
        self.tabControl.setCurrentIndex(1)
        self.cbBaudrate.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyDataLogger V1.0 -KKU-BIMSRL", None))
        self.label.setText(_translate("MainWindow", "Terminal:", None))
        self.btnClear.setText(_translate("MainWindow", "Clear", None))
        self.btnPlot.setText(_translate("MainWindow", "Plot", None))
        self.label_2.setText(_translate("MainWindow", "Command:", None))
        self.tabControl.setTabText(self.tabControl.indexOf(self.tabCmd), _translate("MainWindow", "Command", None))
        self.label_6.setText(_translate("MainWindow", "Default Serial Port Settings [8-N-1]: (8) data bits, no (N) parity bit, and one (1) stop bit", None))
        self.label_7.setText(_translate("MainWindow", "Serial Thread does not initially start. \n"
" First, click \"ReScan\", then \"Start\" button would be \"Enabled\"", None))
        self.label_3.setText(_translate("MainWindow", "Serial Ports:", None))
        self.cbPorts.setProperty("currentText", _translate("MainWindow", "COM1", None))
        self.cbPorts.setItemText(0, _translate("MainWindow", "COM1", None))
        self.btnRescan.setText(_translate("MainWindow", "ReScan", None))
        self.label_4.setText(_translate("MainWindow", "Baud Rates:", None))
        self.cbBaudrate.setProperty("currentText", _translate("MainWindow", "115200", None))
        self.cbBaudrate.setItemText(0, _translate("MainWindow", "1200", None))
        self.cbBaudrate.setItemText(1, _translate("MainWindow", "2400", None))
        self.cbBaudrate.setItemText(2, _translate("MainWindow", "4800", None))
        self.cbBaudrate.setItemText(3, _translate("MainWindow", "9600", None))
        self.cbBaudrate.setItemText(4, _translate("MainWindow", "19200", None))
        self.cbBaudrate.setItemText(5, _translate("MainWindow", "38400", None))
        self.cbBaudrate.setItemText(6, _translate("MainWindow", "57600", None))
        self.cbBaudrate.setItemText(7, _translate("MainWindow", "115200", None))
        self.cbBaudrate.setItemText(8, _translate("MainWindow", "230400", None))
        self.label_5.setText(_translate("MainWindow", "Serial Thread:", None))
        self.btnSerialStart.setText(_translate("MainWindow", "Start", None))
        self.tabControl.setTabText(self.tabControl.indexOf(self.tabSerial), _translate("MainWindow", "Serial Setting", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionClear.setText(_translate("MainWindow", "Clear", None))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear Terminal screen...", None))
        self.actionClear.setShortcut(_translate("MainWindow", "Alt+C", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save Terminal text as...", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Alt+S", None))
        self.actionPortsetting.setText(_translate("MainWindow", "portsetting", None))
        self.actionPortsetting.setToolTip(_translate("MainWindow", "Serial port setting...", None))
        self.actionPortsetting.setShortcut(_translate("MainWindow", "Alt+P", None))
        self.actionTerminalsetting.setText(_translate("MainWindow", "terminalsetting", None))
        self.actionTerminalsetting.setToolTip(_translate("MainWindow", "Terminal setting...", None))
        self.actionTerminalsetting.setShortcut(_translate("MainWindow", "Alt+T", None))
        self.actionExit.setText(_translate("MainWindow", "exit", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit the program...", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+X", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout.setToolTip(_translate("MainWindow", "About PySerialTerminal...", None))
        self.actionAbout.setShortcut(_translate("MainWindow", "Alt+A", None))

from pyqtgraph import PlotWidget
import PySerialTerminal_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

